// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.kep.filemakerparser.domain;

import org.kep.filemakerparser.domain.ChurchMaintenance;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ChurchMaintenance_Roo_Configurable {
    
    declare @type: ChurchMaintenance: @Configurable;
    
}
